routes:

  - id: hello-route
    methods: [GET]
    pathTemplate: /hello
    upstreamBaseUri: http://localhost:9000

  - id: slow-route
    methods: [GET]
    pathTemplate: /slow
    upstreamBaseUri: http://localhost:9000

  - id: users-route
    methods: [GET, POST]
    pathTemplate: /users/{id}
    upstreamBaseUri: http://localhost:9001